name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: yarn playwright:deps

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Run Playwright E2E Tests
        run: yarn test:e2e:ci

      - name: Run Playwright Component Tests
        run: yarn test:ct:ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
